version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Kiem tra file CloudFormation..."
      # - pip install cfn-lint && cfn-lint cloudformation-stack.yaml (Bo qua de chay cho nhanh)
  build:
    commands:
      - echo "Build xong."
artifacts:
  files:
    - cloudformation-stack.yaml